version: '3'

networks: 
    lumen :

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - "80:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - lumen
        depends_on: 
            - php
            - mariadb

    php:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - lumen

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: benjol
            MYSQL_USER: benjol
            MYSQL_PASSWORD: benjol
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAG: dev
            SERVICE_NAME: mariadb
        networks: 
            - lumen
