version: '3.3'

services:
    # Router
    router:
        image: aabdulsalams/benjol-router:latest
        container_name: benjol-router
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - benjol-network
    
    # Backend Services
    backend-app:
        image: aabdulsalams/benjol-backend:latest
        container_name: benjol-backend
        restart: unless-stopped
        tty: true
        env_file: 
            - ./environment/.env
        networks:
            - benjol-network
             
    # Web Service	
    web-app:
        image: aabdulsalams/benjol-web:latest
        container_name: benjol-web
        restart: unless-stopped
        tty: true
        networks: 
            - benjol-network
    
    # Database Service
    mariadb:
        image: mariadb:latest
        container_name: benjol-database
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: 
            MYSQL_USER: 
            MYSQL_PASSWORD: 
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mariadb
        volumes:
            - benjol-data:/var/lib/mysql
        networks: 
            - benjol-network

# Docker Networks
networks:
        benjol-network:
            driver: bridge

# Volumes
volumes:
        benjol-data:
            driver: local
