- name: Copy docker compose file
  copy:
    src: docker-compose.yml
    dest: /home/benjol/docker-compose.yml

- name : Create envoronment directory for backend
  file:
    path: /home/benjol/environment
    state: directory

- name: Copy environment
  copy:
    src: environment/.env
    dest: /home/benjol/environment/.env

- name: Run compose up for app
  docker_compose : 
    project_src: /home/benjol
